investimentos = {'APLIC. POUPANÇA', 'APLICACAO', 'DEBITO B3', 'DEB FUNDO'}
resgate_investimento = {'RESGATE POUPANÇA', 'RESGATE', 'CREDITO RESGATE FUNDO', 'CREDITO B3', }
dividendos = {'CRED EVENTO B3', 'CREDITO CASHBACK FUNDOS', 'CASHBACK MENSAL TAG'}
pix_enviado = {'PIX ENVIADO', 'PIX ENVIADO INTERNO'}
pix_recebido = {'PIX DEVOLUCAO RECEBIDA', 'PIX RECEBIDO INTERNO', 'PIX RECEBIDO', }
pagamentos = {'PAGAMENTO DE CONVENIO', 'PAGAMENTO DE TITULO', 'PAGAMENTO ELEKTRO', 'PAGAMENTO FATURA INTER',
              'DEBITO INTERTAG', 'DEB MENSAL. INTERTAG', 'RECARGA CLARO'}
estorno = {'EST PAGAMENTO CONVENIO'}
compras = {'COMPRA CARTAO'}
saque = {'SAQUE 24 HORAS'}
emprestimo = {'CRED ANTECIPACAO FGTS'}
transferencia = {'TRANSFERENCIA A CREDITO', 'TRANSFERENCIA A DEBITO', 'DOC'}
renda = {'TED RECEBIDA PORTABILIDADE'}